name: CI
on:
  pull_request:
  push:
    branches:
      - '**'
jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              elixir: 1.13
              otp: 24.3
          - pair:
              elixir: 1.14
              otp: 25
          - pair:
              elixir: 1.15
              otp: 25
          - pair:
              elixir: 1.16
              otp: 26
          - pair:
              elixir: 1.17
              otp: 27
    steps:
      - uses: actions/checkout@v3

      - name: Set up Elixir
        id: beam
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}

      - name: Deps Cache
        uses: actions/cache@v3
        with:
          path: deps
          key: mix-deps-${{ hashFiles('**/mix.lock') }}

      - run: mix deps.get

      - run: mix deps.compile

      - run: mix test
